{config, pkgs, inputs, vars, ...}:
let
  mcMojave = import ../configs/hypr/mc-mojave-cursor.nix { inherit pkgs; };
  monitor = vars.monitor;
  autoStart = vars.autoStart;
  workspaceRules = vars.workspaceRules;

  cursorTheme = "McMojave";

  mainMod = "SUPER";
  terminal = "alacritty";
  fileManager = "nemo";
  browser = "librewolf";
  menu = "rofi -show drun";
in {
  home-manager.users.shiina = {...}: {
    # Have to use home.file because home-manager module does not allow for multiple monitors :c
    home.file.".config/hypr/hyprland.conf".text = ''
      #autogenerated = 1

      # Configure Monitors
      monitor=,preferred,auto,auto
      ${monitor}

      # Set autoStart
      exec-once = ${autoStart}
      exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

      # Import PyWal Config
      source=~/.cache/wal/colors-hyprland.conf

      # Set cursor Theme
      env = HYPRCURSOR_THEME,${cursorTheme}
      env = HYPRCURSOR_SIZE,30

      # Layerrules
      layerrule = blur,rofi #blur rofi background

      # Workspace rules
      ${workspaceRules}

      # Keybinds
      bind = ${mainMod}, Q, exec, ${terminal}
      bind = ${mainMod}, C, killactive,
      bind = ${mainMod}, M, exit,
      bind = ${mainMod}, E, exec, ${fileManager}
      bind = ${mainMod}, F, exec, ${browser}
      bind = ${mainMod}, V, togglefloating,
      bind = ${mainMod}, R, exec, ${menu}
      bind = ${mainMod}, P, pseudo, # dwindle
      bind = ${mainMod}, J, togglesplit, # dwindle

      # Volume Keys
      binde =, XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
      binde =, XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
      binde =, XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

      # Take Screenshot
      bind =, Print, exec, grimblast --freeze copy area

      # Move focus with mainMod + arrow keys
      bind = ${mainMod}, left, movefocus, l
      bind = ${mainMod}, right, movefocus, r
      bind = ${mainMod}, up, movefocus, u
      bind = ${mainMod}, down, movefocus, d

      # Move window with mainMod + shift + arrow keys
      bind = ${mainMod} SHIFT, left, swapwindow, l
      bind = ${mainMod} SHIFT, right, swapwindow, r
      bind = ${mainMod} SHIFT, up, swapwindow, u
      bind = ${mainMod} SHIFT, down, swapwindow, d

      # Switch workspaces with mainMod + [0-9]
      bind = ${mainMod}, 1, workspace, 1
      bind = ${mainMod}, 2, workspace, 2
      bind = ${mainMod}, 3, workspace, 3
      bind = ${mainMod}, 4, workspace, 4
      bind = ${mainMod}, 5, workspace, 5
      bind = ${mainMod}, 6, workspace, 6
      bind = ${mainMod}, 7, workspace, 7
      bind = ${mainMod}, 8, workspace, 8
      bind = ${mainMod}, 9, workspace, 9
      bind = ${mainMod}, 0, workspace, 10

      # Move window to a workspace with mainMod + SHIFT + [0-9]
      bind = ${mainMod} SHIFT, 1, movetoworkspace, 1
      bind = ${mainMod} SHIFT, 2, movetoworkspace, 2
      bind = ${mainMod} SHIFT, 3, movetoworkspace, 3
      bind = ${mainMod} SHIFT, 4, movetoworkspace, 4
      bind = ${mainMod} SHIFT, 5, movetoworkspace, 5
      bind = ${mainMod} SHIFT, 6, movetoworkspace, 6
      bind = ${mainMod} SHIFT, 7, movetoworkspace, 7
      bind = ${mainMod} SHIFT, 8, movetoworkspace, 8
      bind = ${mainMod} SHIFT, 9, movetoworkspace, 9
      bind = ${mainMod} SHIFT, 0, movetoworkspace, 10

      # Scratchpad
      bind = ${mainMod}, S, togglespecialworkspace, magic
      bind = ${mainMod} SHIFT, S, movetoworkspace, special:magic

      # Move/resize windows with mainMod + LMB/RMB and dragging
      bindm = ${mainMod}, mouse:272, movewindow
      bindm = ${mainMod}, mouse:273, resizewindow

      input {
          kb_layout = eu
          kb_variant =
          kb_model =
          kb_options =
          kb_rules =

          follow_mouse = 1

          touchpad {
              natural_scroll = no
          }

          sensitivity = 0.5 # -1.0 - 1.0, 0 means no modification.
          accel_profile = flat
          follow_mouse = 1
      }

      general {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more

          gaps_in = 5
          gaps_out = 5, 15, 15, 15
          border_size = 2
          col.active_border = $color0 $color1 45deg
          col.inactive_border = $color2

          layout = dwindle

          # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
          allow_tearing = false
      }

      decoration {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more

          rounding = 10

          blur {
              enabled = true
              size = 3
              passes = 1
          }
          shadow {
              enabled = yes
              range = 4
              render_power = 3
              color = rgba(1a1a1aee)
          }
      }

      animations {
          enabled = yes

          # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

          bezier = myBezier, 0.05, 0.9, 0.1, 1.05

          animation = windows, 1, 7, myBezier
          animation = windowsOut, 1, 7, default, popin 80%
          animation = border, 1, 10, default
          animation = borderangle, 1, 8, default
          animation = fade, 1, 7, default
          animation = workspaces, 1, 6, default
      }

      dwindle {
          # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
          pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
          preserve_split = yes # you probably want this
      }

      master {
          # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
          new_status = master;
      }

      gestures {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more
          workspace_swipe = off
      }

      misc {
          # See https://wiki.hyprland.org/Configuring/Variables/ for more
          force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
      }
    '';
    home.file.".config/hypr/hyprlock.conf".text = ''
      # Include Pywal colors
      source=~/.cache/wal/colors-hyprland.conf
      $font = Profont IIx Nerd Font Mono 10
      $foreground = $color0
      $background = $color1
      $check = $color2

      general { hide_cursor = true }

      auth {
          fingerprint {
              enabled = true;
              ready_message = fingy owo
              present_message = Scamming :3c
              retry_delay = 250 # in ms
          }
      }

      animations {
          enabled = true
          bezier = linear, 1, 1, 0, 0
          animation = fadeIn, 1, 5, linear
          animation = fadeOut, 1, 5, linear
          animation = inputFieldDots, 1, 2, linear
      }

      background {
          monitor =
          path = screenshot
          blur_passes = 3
      }

      # Funny Bottom :3c
      label {
          monitor =
          text = Reading over peoples shoulders is considered rude in most cultures
          font_size = 20
          font_family = $font
          color = $background

          position = 0, 20
          halign = center
          valign = bottom
      }

      input-field {
          monitor =
          size = 20%, 5%
          outline_thickness = 0
          inner_color = rgba(0, 0, 0, 0.4)

          check_color = $check
          fail_color = $background

          font_color = $foreground
          fade_on_empty = false
          rounding = 10

          font_family = $font
          placeholder_text = Input password...
          fail_text = $PAMFAIL

          # uncomment to use a letter instead of a dot to indicate the typed password
          dots_text_format = 🦊
          # dots_size = 0.4
          dots_spacing = 0.3

          # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
          # hide_input = true

          position = 0, -20
          halign = center
          valign = center
      }

      # TIME
      label {
          monitor =
          text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
          font_size = 90
          font_family = $font
          color = $foreground

          position = -30, 0
          halign = right
          valign = top
      }

      # DATE
      label {
          monitor =
          text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
          font_size = 25
          font_family = $font
          color = $background

          position = -30, -150
          halign = right
          valign = top
      }
    '';
    home.file.".config/hypr/hyprpaper.conf".text = ''
      preload = /home/shiina/.DotNix/configs/hypr/wallpaper.png
      wallpaper = ,/home/shiina/.DotNix/configs/hypr/wallpaper.png
    '';
    home.file.".icons/McMojave".source = "${mcMojave}";
  };
}
